run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default enabled set from golangci-lint
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - stylecheck
    - testableexamples
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/QuoVadis86/go-qianyi-sdk
  govet:
    enable:
      - fieldalignment
      - shadow
  cyclop:
    max-complexity: 20
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  errcheck:
    check-type-assertions: true
    check-blank: true
  revive:
    rules:
      - name: exported
        severity: warning
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  usestdlibvars:
    time-weekday: true
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    os-device: true
    os-file-mode: true
    os-edit: true
    http-method: true
    http-status-code: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - cyclop
        - dupl
        - noctx
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
